import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import { currentUser } from "@clerk/nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <h3> NoAhGrAm </h3>
            <nav className="navigation">
              <Link className="home" href="/">
                Home
              </Link>
              <Link className="profile" href="/profile">
                Profile
              </Link>
              <Link className="post" href="/post">
                Posts&Reviews
              </Link>
              <Link className="profile" href="/add-game">
                Add Post
              </Link>
              <Link className="profile" href="/add-review">
                Add Review
              </Link>
              <SignInButton className="signIn" />
              <SignedIn>
                <UserButton />
              </SignedIn>
            </nav>
          </header>
          <SignedOut></SignedOut>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
